/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * ForZone provides information about which zones should consume this endpoint.
 */
export class DiscoveryV1ForZone {
  /**
   * name represents the name of the zone.
   */
  name: string
}
