/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { IoK8sApimachineryPkgRuntimeRawExtension } from './ioK8sApimachineryPkgRuntimeRawExtension'

/**
 * Event represents a single event to a watched resource.
 */
export class IoK8sApimachineryPkgApisMetaV1WatchEvent {
  /**
   * Object is:  * If Type is Added or Modified: the new state of the object.  * If Type is Deleted: the state of the object immediately before deletion.  * If Type is Error: *Status is recommended; other types may make sense    depending on context.
   */
  object: IoK8sApimachineryPkgRuntimeRawExtension
  type: string
}
