/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { IoK8sApiRbacV1AggregationRule } from './ioK8sApiRbacV1AggregationRule'
import type { IoK8sApiRbacV1PolicyRule } from './ioK8sApiRbacV1PolicyRule'
import type { V1ObjectMeta } from './V1ObjectMeta'

/**
 * ClusterRole is a cluster level, logical grouping of PolicyRules that can be referenced as a unit by a RoleBinding or ClusterRoleBinding.
 */
export class IoK8sApiRbacV1ClusterRole {
  /**
     * AggregationRule is an optional field that describes how to build the Rules for this ClusterRole. If AggregationRule is set, then the Rules are controller managed and direct changes to Rules will be stomped by the controller.
     */
  aggregationRule?: IoK8sApiRbacV1AggregationRule
  /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     */
  apiVersion?: string
  /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     */
  kind?: string
  /**
     * Standard object's metadata.
     */
  metadata?: V1ObjectMeta
  /**
     * Rules holds all the PolicyRules for this ClusterRole
     */
  rules?: Array<IoK8sApiRbacV1PolicyRule>
}
