/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * BoundObjectReference is a reference to an object that a token is bound to.
 */
export interface IoK8sApiAuthenticationV1BoundObjectReference {
  /**
     * API version of the referent.
     */
  apiVersion?: string
  /**
     * Kind of the referent. Valid kinds are 'Pod' and 'Secret'.
     */
  kind?: string
  /**
     * Name of the referent.
     */
  name?: string
  /**
     * UID of the referent.
     */
  uid?: string
}
