/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { IoK8sApiCertificatesV1alpha1ClusterTrustBundle } from './ioK8sApiCertificatesV1alpha1ClusterTrustBundle'
import type { V1ListMeta } from './V1ListMeta'

/**
 * ClusterTrustBundleList is a collection of ClusterTrustBundle objects
 */
export class IoK8sApiCertificatesV1alpha1ClusterTrustBundleList {
  /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     */
  apiVersion?: string
  /**
     * items is a collection of ClusterTrustBundle objects
     */
  items: Array<IoK8sApiCertificatesV1alpha1ClusterTrustBundle>
  /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     */
  kind?: string
  /**
     * metadata contains the list metadata.
     */
  metadata?: V1ListMeta
}
