/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * PriorityLevelConfigurationReference contains information that points to the \"request-priority\" being used.
 */
export class IoK8sApiFlowcontrolV1beta2PriorityLevelConfigurationReference {
  /**
     * `name` is the name of the priority level configuration being referenced Required.
     */
  name: string
}
