/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { IoK8sApiAppsV1ReplicaSetCondition } from './ioK8sApiAppsV1ReplicaSetCondition'

/**
 * ReplicaSetStatus represents the current status of a ReplicaSet.
 */
export interface IoK8sApiAppsV1ReplicaSetStatus {
  /**
     * The number of available replicas (ready for at least minReadySeconds) for this replica set.
     */
  availableReplicas?: number
  /**
     * Represents the latest available observations of a replica set's current state.
     */
  conditions?: Array<IoK8sApiAppsV1ReplicaSetCondition>
  /**
     * The number of pods that have labels matching the labels of the pod template of the replicaset.
     */
  fullyLabeledReplicas?: number
  /**
     * ObservedGeneration reflects the generation of the most recently observed ReplicaSet.
     */
  observedGeneration?: number
  /**
     * readyReplicas is the number of pods targeted by this ReplicaSet with a Ready Condition.
     */
  readyReplicas?: number
  /**
     * Replicas is the most recently observed number of replicas. More info: https://kubernetes.io/docs/concepts/workloads/controllers/replicationcontroller/#what-is-a-replicationcontroller
     */
  replicas: number
}
