/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * ParentReference describes a reference to a parent object.
 */
export class IoK8sApiNetworkingV1alpha1ParentReference {
  /**
     * Group is the group of the object being referenced.
     */
  group?: string
  /**
     * Name is the name of the object being referenced.
     */
  name?: string
  /**
     * Namespace is the namespace of the object being referenced.
     */
  namespace?: string
  /**
     * Resource is the resource of the object being referenced.
     */
  resource?: string
  /**
     * UID is the uid of the object being referenced.
     */
  uid?: string
}
