/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { V1Time } from './V1Time'

/**
 * TokenRequestStatus is the result of a token request.
 */
export class IoK8sApiAuthenticationV1TokenRequestStatus {
  /**
   * ExpirationTimestamp is the time of expiration of the returned token.
   */
  expirationTimestamp: V1Time
  /**
   * Token is the opaque bearer token.
   */
  token: string
}
