/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * UserSubject holds detailed information for user-kind subject.
 */
export class IoK8sApiFlowcontrolV1beta2UserSubject {
  /**
     * `name` is the username that matches, or \"*\" to match all usernames. Required.
     */
  name: string
}
