/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { IoK8sApiResourceV1alpha2ResourceClaimTemplateSpec } from './ioK8sApiResourceV1alpha2ResourceClaimTemplateSpec'
import type { V1ObjectMeta } from './V1ObjectMeta'

/**
 * ResourceClaimTemplate is used to produce ResourceClaim objects.
 */
export class IoK8sApiResourceV1alpha2ResourceClaimTemplate {
  /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     */
  apiVersion?: string
  /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     */
  kind?: string
  /**
     * Standard object metadata
     */
  metadata?: V1ObjectMeta
  /**
     * Describes the ResourceClaim that is to be generated.  This field is immutable. A ResourceClaim will get created by the control plane for a Pod when needed and then not get updated anymore.
     */
  spec: IoK8sApiResourceV1alpha2ResourceClaimTemplateSpec
}
