/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * ExternalDocumentation allows referencing an external resource for extended documentation.
 */
export class IoK8sApiextensionsApiserverPkgApisApiextensionsV1ExternalDocumentation {
  description?: string
  url?: string
}
