/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { V1ObjectReference } from './V1ObjectReference'
import type { V1Time } from './V1Time'

/**
 * CronJobStatus represents the current state of a cron job.
 */
export interface IoK8sApiBatchV1CronJobStatus {
  /**
     * A list of pointers to currently running jobs.
     */
  active?: Array<V1ObjectReference>
  /**
     * Information when was the last time the job was successfully scheduled.
     */
  lastScheduleTime?: V1Time
  /**
     * Information when was the last time the job successfully completed.
     */
  lastSuccessfulTime?: V1Time
}
