/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { IoK8sApiAuthenticationV1UserInfo } from './ioK8sApiAuthenticationV1UserInfo'

/**
 * SelfSubjectReviewStatus is filled by the kube-apiserver and sent back to a user.
 */
export class IoK8sApiAuthenticationV1beta1SelfSubjectReviewStatus {
  /**
     * User attributes of the user making this request.
     */
  userInfo?: IoK8sApiAuthenticationV1UserInfo
}
