/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * RoleRef contains information that points to the role being used
 */
export class IoK8sApiRbacV1RoleRef {
  /**
     * APIGroup is the group for the resource being referenced
     */
  apiGroup: string
  /**
     * Kind is the type of resource being referenced
     */
  kind: string
  /**
     * Name is the name of resource being referenced
     */
  name: string
}
