/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * TokenRequest contains parameters of a service account token.
 */
export class IoK8sApiStorageV1TokenRequest {
  /**
     * audience is the intended audience of the token in \"TokenRequestSpec\". It will default to the audiences of kube apiserver.
     */
  audience: string
  /**
     * expirationSeconds is the duration of validity of the token in \"TokenRequestSpec\". It has the same default value of \"ExpirationSeconds\" in \"TokenRequestSpec\".
     */
  expirationSeconds?: number
}
