/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * NonResourceAttributes includes the authorization attributes available for non-resource requests to the Authorizer interface
 */
export interface IoK8sApiAuthorizationV1NonResourceAttributes {
  /**
     * Path is the URL path of the request
     */
  path?: string
  /**
     * Verb is the standard HTTP verb
     */
  verb?: string
}
