/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionCondition } from './ioK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionCondition'
import type { IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionNames } from './ioK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionNames'

/**
 * CustomResourceDefinitionStatus indicates the state of the CustomResourceDefinition
 */
export interface IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionStatus {
  /**
     * acceptedNames are the names that are actually being used to serve discovery. They may be different than the names in spec.
     */
  acceptedNames?: IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionNames
  /**
     * conditions indicate state for particular aspects of a CustomResourceDefinition
     */
  conditions?: Array<IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionCondition>
  /**
     * storedVersions lists all versions of CustomResources that were ever persisted. Tracking these versions allows a migration path for stored versions in etcd. The field is mutable so a migration controller can finish a migration to another version (ensuring no old objects are left in storage), and then remove the rest of the versions from this list. Versions may not be removed from `spec.versions` while they exist in this list.
     */
  storedVersions?: Array<string>
}
