/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { IoK8sApiFlowcontrolV1beta2QueuingConfiguration } from './ioK8sApiFlowcontrolV1beta2QueuingConfiguration'

/**
 * LimitResponse defines how to handle requests that can not be executed right now.
 */
export class IoK8sApiFlowcontrolV1beta2LimitResponse {
  /**
     * `queuing` holds the configuration parameters for queuing. This field may be non-empty only if `type` is `\"Queue\"`.
     */
  queuing?: IoK8sApiFlowcontrolV1beta2QueuingConfiguration
  /**
     * `type` is \"Queue\" or \"Reject\". \"Queue\" means that requests that can not be executed upon arrival are held in a queue until they can be executed or a queuing limit is reached. \"Reject\" means that requests that can not be executed upon arrival are rejected. Required.
     */
  type: string
}
