/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { IoK8sApiResourceV1alpha2ResourceClaimSpec } from './ioK8sApiResourceV1alpha2ResourceClaimSpec'
import type { IoK8sApiResourceV1alpha2ResourceClaimStatus } from './ioK8sApiResourceV1alpha2ResourceClaimStatus'
import type { V1ObjectMeta } from './V1ObjectMeta'

/**
 * ResourceClaim describes which resources are needed by a resource consumer. Its status tracks whether the resource has been allocated and what the resulting attributes are.  This is an alpha type and requires enabling the DynamicResourceAllocation feature gate.
 */
export class IoK8sApiResourceV1alpha2ResourceClaim {
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   */
  apiVersion?: string
  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   */
  kind?: string
  /**
   * Standard object metadata
   */
  metadata?: V1ObjectMeta
  /**
   * Spec describes the desired attributes of a resource that then needs to be allocated. It can only be set once when creating the ResourceClaim.
   */
  spec: IoK8sApiResourceV1alpha2ResourceClaimSpec
  /**
   * Status describes whether the resource is available and with which attributes.
   */
  status?: IoK8sApiResourceV1alpha2ResourceClaimStatus
}
