/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { IoK8sApiAuthorizationV1NonResourceAttributes } from './ioK8sApiAuthorizationV1NonResourceAttributes'
import type { IoK8sApiAuthorizationV1ResourceAttributes } from './ioK8sApiAuthorizationV1ResourceAttributes'

/**
 * SubjectAccessReviewSpec is a description of the access request.  Exactly one of ResourceAuthorizationAttributes and NonResourceAuthorizationAttributes must be set
 */
export class IoK8sApiAuthorizationV1SubjectAccessReviewSpec {
  /**
     * Extra corresponds to the user.Info.GetExtra() method from the authenticator.  Since that is input to the authorizer it needs a reflection here.
     */
  extra?: { [key: string]: Array<string> }
  /**
     * Groups is the groups you're testing for.
     */
  groups?: Array<string>
  /**
     * NonResourceAttributes describes information for a non-resource access request
     */
  nonResourceAttributes?: IoK8sApiAuthorizationV1NonResourceAttributes
  /**
     * ResourceAuthorizationAttributes describes information for a resource access request
     */
  resourceAttributes?: IoK8sApiAuthorizationV1ResourceAttributes
  /**
     * UID information about the requesting user.
     */
  uid?: string
  /**
     * User is the user you're testing for. If you specify \"User\" but not \"Groups\", then is it interpreted as \"What if User were not a member of any groups
     */
  user?: string
}
