/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * AzureFile represents an Azure File Service mount on the host and bind mount to the pod.
 */
export class V1AzureFilePersistentVolumeSource {
  /**
     * readOnly defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts.
     */
  readOnly?: boolean
  /**
     * secretName is the name of secret that contains Azure Storage Account Name and Key
     */
  secretName: string
  /**
     * secretNamespace is the namespace of the secret that contains Azure Storage Account Name and Key default is the same as the Pod
     */
  secretNamespace?: string
  /**
     * shareName is the azure Share Name
     */
  shareName: string
}
