/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Adds and removes POSIX capabilities from running containers.
 */
export class V1Capabilities {
  /**
   * Added capabilities
   */
  add?: Array<string>
  /**
   * Removed capabilities
   */
  drop?: Array<string>
}
