/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * ContainerStateWaiting is a waiting state of a container.
 */
export class V1ContainerStateWaiting {
  /**
   * Message regarding why the container is not yet running.
   */
  message?: string
  /**
   * (brief) reason the container is not yet running.
   */
  reason?: string
}
