/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { V1Time } from './V1Time'

/**
 * ContainerStateTerminated is a terminated state of a container.
 */
export interface V1ContainerStateTerminated {
  /**
     * Container's ID in the format '<type>://<container_id>'
     */
  containerID?: string
  /**
     * Exit status from the last termination of the container
     */
  exitCode: number
  /**
     * Time at which the container last terminated
     */
  finishedAt?: V1Time
  /**
     * Message regarding the last termination of the container
     */
  message?: string
  /**
     * (brief) reason from the last termination of the container
     */
  reason?: string
  /**
     * Signal from the last termination of the container
     */
  signal?: number
  /**
     * Time at which previous execution of the container started
     */
  startedAt?: V1Time
}
