/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { IoK8sApiAppsV1DaemonSetUpdateStrategy } from './ioK8sApiAppsV1DaemonSetUpdateStrategy'
import type { V1PodTemplateSpec } from './V1PodTemplateSpec'
import type { V1LabelSelector } from './v1LabelSelector'

/**
 * DaemonSetSpec is the specification of a daemon set.
 */
export interface V1DaemonSetSpec {
  /**
     * The minimum number of seconds for which a newly created DaemonSet pod should be ready without any of its container crashing, for it to be considered available. Defaults to 0 (pod will be considered available as soon as it is ready).
     */
  minReadySeconds?: number
  /**
     * The number of old history to retain to allow rollback. This is a pointer to distinguish between explicit zero and not specified. Defaults to 10.
     */
  revisionHistoryLimit?: number
  /**
     * A label query over pods that are managed by the daemon set. Must match in order to be controlled. It must match the pod template's labels. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors
     */
  selector: V1LabelSelector
  /**
     * An object that describes the pod that will be created. The DaemonSet will create exactly one copy of this pod on every node that matches the template's node selector (or on every node if no node selector is specified). The only allowed template.spec.restartPolicy value is \"Always\". More info: https://kubernetes.io/docs/concepts/workloads/controllers/replicationcontroller#pod-template
     */
  template: V1PodTemplateSpec
  /**
     * An update strategy to replace existing DaemonSet pods with new pods.
     */
  updateStrategy?: IoK8sApiAppsV1DaemonSetUpdateStrategy
}
