/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { IoK8sApimachineryPkgApisMetaV1MicroTime } from './ioK8sApimachineryPkgApisMetaV1MicroTime'

/**
 * EventSeries contain information on series of events, i.e. thing that was/is happening continuously for some time.
 */
export class V1EventSeries {
  /**
     * Number of occurrences in this series up to the last heartbeat time
     */
  count?: number
  /**
     * Time of the last occurrence observed
     */
  lastObservedTime?: IoK8sApimachineryPkgApisMetaV1MicroTime
}
