/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { V1TypedLocalObjectReference } from './V1TypedLocalObjectReference'
import type { V1IngressServiceBackend } from './v1IngressServiceBackend'

/**
 * IngressBackend describes all endpoints for a given service and port.
 */
export class V1IngressBackend {
  /**
     * resource is an ObjectRef to another Kubernetes resource in the namespace of the Ingress object. If resource is specified, a service.Name and service.Port must not be specified. This is a mutually exclusive setting with \"Service\".
     */
  resource?: V1TypedLocalObjectReference
  /**
     * service references a service as a backend. This is a mutually exclusive setting with \"Resource\".
     */
  service?: V1IngressServiceBackend
}
