/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { V1PortStatus } from './V1PortStatus'

/**
 * LoadBalancerIngress represents the status of a load-balancer ingress point: traffic intended for the service should be sent to an ingress point.
 */
export class V1LoadBalancerIngress {
  /**
     * Hostname is set for load-balancer ingress points that are DNS based (typically AWS load-balancers)
     */
  hostname?: string
  /**
     * IP is set for load-balancer ingress points that are IP based (typically GCE or OpenStack load-balancers)
     */
  ip?: string
  /**
     * Ports is a list of records of service ports If used, every port defined in the service should have an entry in it
     */
  ports?: Array<V1PortStatus>
}
