/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { V1LoadBalancerIngress } from './V1LoadBalancerIngress'

/**
 * LoadBalancerStatus represents the status of a load-balancer.
 */
export interface V1LoadBalancerStatus {
  /**
     * Ingress is a list containing ingress points for the load-balancer. Traffic intended for the service should be sent to these ingress points.
     */
  ingress?: Array<V1LoadBalancerIngress>
}
