/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { V1NodeSelectorTerm } from './V1NodeSelectorTerm'

/**
 * A node selector represents the union of the results of one or more label queries over a set of nodes; that is, it represents the OR of the selectors represented by the node selector terms.
 */
export class V1NodeSelector {
  /**
     * Required. A list of node selector terms. The terms are ORed.
     */
  nodeSelectorTerms: Array<V1NodeSelectorTerm>
}
