/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { V1NodeSelectorRequirement } from './V1NodeSelectorRequirement'

/**
 * A null or empty node selector term matches no objects. The requirements of them are ANDed. The TopologySelectorTerm type implements a subset of the NodeSelectorTerm.
 */
export interface V1NodeSelectorTerm {
  /**
     * A list of node selector requirements by node's labels.
     */
  matchExpressions?: Array<V1NodeSelectorRequirement>
  /**
     * A list of node selector requirements by node's fields.
     */
  matchFields?: Array<V1NodeSelectorRequirement>
}
