/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { V1ConfigMapNodeConfigSource } from './V1ConfigMapNodeConfigSource'

/**
 * NodeConfigSource specifies a source of node configuration. Exactly one subfield (excluding metadata) must be non-nil. This API is deprecated since 1.22
 */
export class V1NodeConfigSource {
  /**
     * ConfigMap is a reference to a Node's ConfigMap
     */
  configMap?: V1ConfigMapNodeConfigSource
}
