/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { V1PersistentVolumeClaimCondition } from './V1PersistentVolumeClaimCondition'
import type { ResourceQuantity } from './resourceQuantity'

/**
 * PersistentVolumeClaimStatus is the current status of a persistent volume claim.
 */
export class V1PersistentVolumeClaimStatus {
  /**
   * accessModes contains the actual access modes the volume backing the PVC has. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1
   */
  accessModes?: Array<string>
  /**
   * allocatedResources is the storage resource within AllocatedResources tracks the capacity allocated to a PVC. It may be larger than the actual capacity when a volume expansion operation is requested. For storage quota, the larger value from allocatedResources and PVC.spec.resources is used. If allocatedResources is not set, PVC.spec.resources alone is used for quota calculation. If a volume expansion capacity request is lowered, allocatedResources is only lowered if there are no expansion operations in progress and if the actual volume capacity is equal or lower than the requested capacity. This is an alpha field and requires enabling RecoverVolumeExpansionFailure feature.
   */
  allocatedResources?: { [key: string]: ResourceQuantity }
  /**
   * capacity represents the actual resources of the underlying volume.
   */
  capacity?: { [key: string]: ResourceQuantity }
  /**
   * conditions is the current Condition of persistent volume claim. If underlying persistent volume is being resized then the Condition will be set to 'ResizeStarted'.
   */
  conditions?: Array<V1PersistentVolumeClaimCondition>
  /**
   * phase represents the current phase of PersistentVolumeClaim.
   */
  phase?: string
  /**
   * resizeStatus stores status of resize operation. ResizeStatus is not set by default but when expansion is complete resizeStatus is set to empty string by resize controller or kubelet. This is an alpha field and requires enabling RecoverVolumeExpansionFailure feature.
   */
  resizeStatus?: string
}
