/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { V1ClaimSource } from './V1ClaimSource'

/**
 * PodResourceClaim references exactly one ResourceClaim through a ClaimSource. It adds a name to it that uniquely identifies the ResourceClaim inside the Pod. Containers that need access to the ResourceClaim reference it with this name.
 */
export class V1PodResourceClaim {
  /**
   * Name uniquely identifies this resource claim inside the pod. This must be a DNS_LABEL.
   */
  name: string
  /**
   * Source describes where to find the ResourceClaim.
   */
  source?: V1ClaimSource
}
