/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * PodDNSConfigOption defines DNS resolver options of a pod.
 */
export class V1PodDNSConfigOption {
  /**
     * Required.
     */
  name?: string
  value?: string
}
