/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * PodSchedulingGate is associated to a Pod to guard its scheduling.
 */
export class V1PodSchedulingGate {
  /**
     * Name of the scheduling gate. Each scheduling gate must have a unique name field.
     */
  name: string
}
