/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { V1NodeSelectorTerm } from './V1NodeSelectorTerm'

/**
 * An empty preferred scheduling term matches all objects with implicit weight 0 (i.e. it's a no-op). A null preferred scheduling term matches no objects (i.e. is also a no-op).
 */
export class V1PreferredSchedulingTerm {
  /**
     * A node selector term, associated with the corresponding weight.
     */
  preference: V1NodeSelectorTerm
  /**
     * Weight associated with matching the corresponding nodeSelectorTerm, in the range 1-100.
     */
  weight: number
}
