/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { V1ClientIPConfig } from './V1ClientIPConfig'

/**
 * SessionAffinityConfig represents the configurations of session affinity.
 */
export class V1SessionAffinityConfig {
  /**
     * clientIP contains the configurations of Client IP based session affinity.
     */
  clientIP?: V1ClientIPConfig
}
