/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { V1TopologySelectorLabelRequirement } from './V1TopologySelectorLabelRequirement'

/**
 * A topology selector term represents the result of label queries. A null or empty topology selector term matches no objects. The requirements of them are ANDed. It provides a subset of functionality as NodeSelectorTerm. This is an alpha feature and may change in the future.
 */
export class V1TopologySelectorTerm {
  /**
   * A list of topology selector requirements by labels.
   */
  matchLabelExpressions?: Array<V1TopologySelectorLabelRequirement>
}
