/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { V1Time } from './V1Time'

/**
 * HorizontalPodAutoscalerCondition describes the state of a HorizontalPodAutoscaler at a certain point.
 */
export class V2HorizontalPodAutoscalerCondition {
  /**
     * lastTransitionTime is the last time the condition transitioned from one status to another
     */
  lastTransitionTime?: V1Time
  /**
     * message is a human-readable explanation containing details about the transition
     */
  message?: string
  /**
     * reason is the reason for the condition's last transition.
     */
  reason?: string
  /**
     * status is the status of the condition (True, False, Unknown)
     */
  status: string
  /**
     * type describes the current condition
     */
  type: string
}
