/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { IoK8sApiAutoscalingV2HorizontalPodAutoscalerCondition } from './ioK8sApiAutoscalingV2HorizontalPodAutoscalerCondition'
import type { IoK8sApiAutoscalingV2MetricStatus } from './ioK8sApiAutoscalingV2MetricStatus'
import type { V1Time } from './V1Time'

/**
 * HorizontalPodAutoscalerStatus describes the current status of a horizontal pod autoscaler.
 */
export interface V2HorizontalPodAutoscalerStatus {
  /**
     * conditions is the set of conditions required for this autoscaler to scale its target, and indicates whether or not those conditions are met.
     */
  conditions?: Array<IoK8sApiAutoscalingV2HorizontalPodAutoscalerCondition>
  /**
     * currentMetrics is the last read state of the metrics used by this autoscaler.
     */
  currentMetrics?: Array<IoK8sApiAutoscalingV2MetricStatus>
  /**
     * currentReplicas is current number of replicas of pods managed by this autoscaler, as last seen by the autoscaler.
     */
  currentReplicas?: number
  /**
     * desiredReplicas is the desired number of replicas of pods managed by this autoscaler, as last calculated by the autoscaler.
     */
  desiredReplicas: number
  /**
     * lastScaleTime is the last time the HorizontalPodAutoscaler scaled the number of pods, used by the autoscaler to control how often the number of pods is changed.
     */
  lastScaleTime?: V1Time
  /**
     * observedGeneration is the most recent generation observed by this autoscaler.
     */
  observedGeneration?: number
}
