/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { IoK8sApiAutoscalingV2ContainerResourceMetricSource } from './ioK8sApiAutoscalingV2ContainerResourceMetricSource'
import type { IoK8sApiAutoscalingV2ExternalMetricSource } from './ioK8sApiAutoscalingV2ExternalMetricSource'
import type { IoK8sApiAutoscalingV2ObjectMetricSource } from './ioK8sApiAutoscalingV2ObjectMetricSource'
import type { IoK8sApiAutoscalingV2PodsMetricSource } from './ioK8sApiAutoscalingV2PodsMetricSource'
import type { V2ResourceMetricSource } from './v2ResourceMetricSource'

/**
 * MetricSpec specifies how to scale based on a single metric (only `type` and one other matching field should be set at once).
 */
export class V2MetricSpec {
  /**
     * containerResource refers to a resource metric (such as those specified in requests and limits) known to Kubernetes describing a single container in each pod of the current scale target (e.g. CPU or memory). Such metrics are built in to Kubernetes, and have special scaling options on top of those available to normal per-pod metrics using the \"pods\" source. This is an alpha feature and can be enabled by the HPAContainerMetrics feature flag.
     */
  containerResource?: IoK8sApiAutoscalingV2ContainerResourceMetricSource
  /**
     * external refers to a global metric that is not associated with any Kubernetes object. It allows autoscaling based on information coming from components running outside of cluster (for example length of queue in cloud messaging service, or QPS from loadbalancer running outside of cluster).
     */
  external?: IoK8sApiAutoscalingV2ExternalMetricSource
  /**
     * object refers to a metric describing a single kubernetes object (for example, hits-per-second on an Ingress object).
     */
  object?: IoK8sApiAutoscalingV2ObjectMetricSource
  /**
     * pods refers to a metric describing each pod in the current scale target (for example, transactions-processed-per-second).  The values will be averaged together before being compared to the target value.
     */
  pods?: IoK8sApiAutoscalingV2PodsMetricSource
  /**
     * resource refers to a resource metric (such as those specified in requests and limits) known to Kubernetes describing each pod in the current scale target (e.g. CPU or memory). Such metrics are built in to Kubernetes, and have special scaling options on top of those available to normal per-pod metrics using the \"pods\" source.
     */
  resource?: V2ResourceMetricSource
  /**
     * type is the type of metric source.  It should be one of \"ContainerResource\", \"External\", \"Object\", \"Pods\" or \"Resource\", each mapping to a matching field in the object. Note: \"ContainerResource\" type is available on when the feature-gate HPAContainerMetrics is enabled
     */
  type: string
}
