/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { V1LabelSelector } from './v1LabelSelector'

/**
 * MetricIdentifier defines the name and optionally selector for a metric
 */
export interface V2MetricIdentifier {
  /**
     * name is the name of the given metric
     */
  name: string
  /**
     * selector is the string-encoded form of a standard kubernetes label selector for the given metric When set, it is passed as an additional parameter to the metrics server for more specific metrics scoping. When unset, just the metricName will be used to gather metrics.
     */
  selector?: V1LabelSelector
}
