/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { ResourceQuantity } from './resourceQuantity'

/**
 * MetricTarget defines the target value, average value, or average utilization of a specific metric
 */
export class V2MetricTarget {
  /**
     * averageUtilization is the target value of the average of the resource metric across all relevant pods, represented as a percentage of the requested value of the resource for the pods. Currently only valid for Resource metric source type
     */
  averageUtilization?: number
  /**
     * averageValue is the target value of the average of the metric across all relevant pods (as a quantity)
     */
  averageValue?: ResourceQuantity
  /**
     * type represents whether the metric type is Utilization, Value, or AverageValue
     */
  type: string
  /**
     * value is the target value of the metric (as a quantity).
     */
  value?: ResourceQuantity
}
