/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { IoK8sApiFlowcontrolV1beta2NonResourcePolicyRule } from './ioK8sApiFlowcontrolV1beta2NonResourcePolicyRule'
import type { IoK8sApiFlowcontrolV1beta2ResourcePolicyRule } from './ioK8sApiFlowcontrolV1beta2ResourcePolicyRule'
import type { IoK8sApiFlowcontrolV1beta2Subject } from './ioK8sApiFlowcontrolV1beta2Subject'

/**
 * PolicyRulesWithSubjects prescribes a test that applies to a request to an apiserver. The test considers the subject making the request, the verb being requested, and the resource to be acted upon. This PolicyRulesWithSubjects matches a request if and only if both (a) at least one member of subjects matches the request and (b) at least one member of resourceRules or nonResourceRules matches the request.
 */
export interface IoK8sApiFlowcontrolV1beta2PolicyRulesWithSubjects {
  /**
     * `nonResourceRules` is a list of NonResourcePolicyRules that identify matching requests according to their verb and the target non-resource URL.
     */
  nonResourceRules?: Array<IoK8sApiFlowcontrolV1beta2NonResourcePolicyRule>
  /**
     * `resourceRules` is a slice of ResourcePolicyRules that identify matching requests according to their verb and the target resource. At least one of `resourceRules` and `nonResourceRules` has to be non-empty.
     */
  resourceRules?: Array<IoK8sApiFlowcontrolV1beta2ResourcePolicyRule>
  /**
     * subjects is the list of normal user, serviceaccount, or group that this rule cares about. There must be at least one member in this slice. A slice that includes both the system:authenticated and system:unauthenticated user groups matches every request. Required.
     */
  subjects: Array<IoK8sApiFlowcontrolV1beta2Subject>
}
