/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { IoK8sApiAppsV1RollingUpdateDaemonSet } from './ioK8sApiAppsV1RollingUpdateDaemonSet'

/**
 * DaemonSetUpdateStrategy is a struct used to control the update strategy for a DaemonSet.
 */
export interface IoK8sApiAppsV1DaemonSetUpdateStrategy {
  /**
     * Rolling update config params. Present only if type = \"RollingUpdate\".
     */
  rollingUpdate?: IoK8sApiAppsV1RollingUpdateDaemonSet
  /**
     * Type of daemon set update. Can be \"RollingUpdate\" or \"OnDelete\". Default is RollingUpdate.
     */
  type?: string
}
