/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { IoK8sApiAdmissionregistrationV1alpha1ExpressionWarning } from './ioK8sApiAdmissionregistrationV1alpha1ExpressionWarning'

/**
 * TypeChecking contains results of type checking the expressions in the ValidatingAdmissionPolicy
 */
export interface IoK8sApiAdmissionregistrationV1alpha1TypeChecking {
  /**
     * The type checking warnings for each expression.
     */
  expressionWarnings?: Array<IoK8sApiAdmissionregistrationV1alpha1ExpressionWarning>
}
