/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * UncountedTerminatedPods holds UIDs of Pods that have terminated but haven't been accounted in Job status counters.
 */
export interface IoK8sApiBatchV1UncountedTerminatedPods {
  /**
     * failed holds UIDs of failed Pods.
     */
  failed?: Array<string>
  /**
     * succeeded holds UIDs of succeeded Pods.
     */
  succeeded?: Array<string>
}
