/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { IoK8sApiAutoscalingV1HorizontalPodAutoscalerSpec } from './ioK8sApiAutoscalingV1HorizontalPodAutoscalerSpec'
import type { IoK8sApiAutoscalingV1HorizontalPodAutoscalerStatus } from './ioK8sApiAutoscalingV1HorizontalPodAutoscalerStatus'
import type { V1ObjectMeta } from './V1ObjectMeta'

/**
 * configuration of a horizontal pod autoscaler.
 */
export interface IoK8sApiAutoscalingV1HorizontalPodAutoscaler {
  /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     */
  apiVersion?: string
  /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     */
  kind?: string
  /**
     * Standard object metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
     */
  metadata?: V1ObjectMeta
  /**
     * spec defines the behaviour of autoscaler. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status.
     */
  spec?: IoK8sApiAutoscalingV1HorizontalPodAutoscalerSpec
  /**
     * status is the current information about the autoscaler.
     */
  status?: IoK8sApiAutoscalingV1HorizontalPodAutoscalerStatus
}
