/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { IoK8sApimachineryPkgApisMetaV1Time } from './ioK8sApimachineryPkgApisMetaV1Time'

/**
 * APIServiceCondition describes the state of an APIService at a particular point
 */
export interface IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceCondition {
  /**
     * Last time the condition transitioned from one status to another.
     */
  lastTransitionTime?: IoK8sApimachineryPkgApisMetaV1Time
  /**
     * Human-readable message indicating details about last transition.
     */
  message?: string
  /**
     * Unique, one-word, CamelCase reason for the condition's last transition.
     */
  reason?: string
  /**
     * Status is the status of the condition. Can be True, False, Unknown.
     */
  status: string
  /**
     * Type is the type of the condition.
     */
  type: string
}
