/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { IoK8sApiResourceV1alpha2ResourceClaimSpec } from './ioK8sApiResourceV1alpha2ResourceClaimSpec'
import type { V1ObjectMeta } from './V1ObjectMeta'

/**
 * ResourceClaimTemplateSpec contains the metadata and fields for a ResourceClaim.
 */
export interface IoK8sApiResourceV1alpha2ResourceClaimTemplateSpec {
  /**
     * ObjectMeta may contain labels and annotations that will be copied into the PVC when creating it. No other fields are allowed and will be rejected during validation.
     */
  metadata?: V1ObjectMeta
  /**
     * Spec for the ResourceClaim. The entire content is copied unchanged into the ResourceClaim that gets created from this template. The same fields as in a ResourceClaim are also valid here.
     */
  spec: IoK8sApiResourceV1alpha2ResourceClaimSpec
}
