/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { IoK8sApimachineryPkgApisMetaV1Time } from './ioK8sApimachineryPkgApisMetaV1Time'

/**
 * Condition contains details for one aspect of the current state of this API Resource.
 */
export interface IoK8sApimachineryPkgApisMetaV1Condition {
  /**
     * lastTransitionTime is the last time the condition transitioned from one status to another. This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
     */
  lastTransitionTime: IoK8sApimachineryPkgApisMetaV1Time
  /**
     * message is a human readable message indicating details about the transition. This may be an empty string.
     */
  message: string
  /**
     * observedGeneration represents the .metadata.generation that the condition was set based upon. For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date with respect to the current state of the instance.
     */
  observedGeneration?: number
  /**
     * reason contains a programmatic identifier indicating the reason for the condition's last transition. Producers of specific condition types may define expected values and meanings for this field, and whether the values are considered a guaranteed API. The value should be a CamelCase string. This field may not be empty.
     */
  reason: string
  /**
     * status of the condition, one of True, False, Unknown.
     */
  status: string
  /**
     * type of condition in CamelCase or in foo.example.com/CamelCase.
     */
  type: string
}
