/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { IoK8sApiStorageV1CSINodeDriver } from './ioK8sApiStorageV1CSINodeDriver'

/**
 * CSINodeSpec holds information about the specification of all CSI drivers installed on a node
 */
export interface IoK8sApiStorageV1CSINodeSpec {
  /**
     * drivers is a list of information of all CSI Drivers existing on a node. If all drivers in the list are uninstalled, this can become empty.
     */
  drivers: Array<IoK8sApiStorageV1CSINodeDriver>
}
