/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { IoK8sApiextensionsApiserverPkgApisApiextensionsV1JSONSchemaProps } from './ioK8sApiextensionsApiserverPkgApisApiextensionsV1JSONSchemaProps'

/**
 * CustomResourceValidation is a list of validation methods for CustomResources.
 */
export interface IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceValidation {
  /**
     * openAPIV3Schema is the OpenAPI v3 schema to use for validation and pruning.
     */
  openAPIV3Schema?: IoK8sApiextensionsApiserverPkgApisApiextensionsV1JSONSchemaProps
}
