/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * An API server instance reports the version it can decode and the version it encodes objects to when persisting objects in the backend.
 */
export interface IoK8sApiApiserverinternalV1alpha1ServerStorageVersion {
  /**
     * The ID of the reporting API server.
     */
  apiServerID?: string
  /**
     * The API server can decode objects encoded in these versions. The encodingVersion must be included in the decodableVersions.
     */
  decodableVersions?: Array<string>
  /**
     * The API server encodes the object to this version when persisting it in the backend (e.g., etcd).
     */
  encodingVersion?: string
}
