/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { IoK8sApimachineryPkgApisMetaV1Time } from './ioK8sApimachineryPkgApisMetaV1Time'

/**
 * ContainerStateRunning is a running state of a container.
 */
export interface V1ContainerStateRunning {
  /**
     * Time at which the container was last (re-)started
     */
  startedAt?: IoK8sApimachineryPkgApisMetaV1Time
}
