/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { V1DownwardAPIVolumeFile } from './V1DownwardAPIVolumeFile'

/**
 * Represents downward API info for projecting into a projected volume. Note that this is identical to a downwardAPI volume source without the default mode.
 */
export interface V1DownwardAPIProjection {
  /**
     * Items is a list of DownwardAPIVolume file
     */
  items?: Array<V1DownwardAPIVolumeFile>
}
