/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * HTTPHeader describes a custom header to be used in HTTP probes
 */
export interface V1HTTPHeader {
  /**
     * The header field name. This will be canonicalized upon output, so case-variant names will be understood as the same header.
     */
  name: string
  /**
     * The header field value
     */
  value: string
}
