/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { V1ExecAction } from './V1ExecAction'
import type { V1HTTPGetAction } from './V1HTTPGetAction'
import type { V1TCPSocketAction } from './V1TCPSocketAction'

/**
 * LifecycleHandler defines a specific action that should be taken in a lifecycle hook. One and only one of the fields, except TCPSocket must be specified.
 */
export interface V1LifecycleHandler {
  /**
     * Exec specifies the action to take.
     */
  exec?: V1ExecAction
  /**
     * HTTPGet specifies the http request to perform.
     */
  httpGet?: V1HTTPGetAction
  /**
     * Deprecated. TCPSocket is NOT supported as a LifecycleHandler and kept for the backward compatibility. There are no validation of this field and lifecycle hooks will fail in runtime when tcp handler is specified.
     */
  tcpSocket?: V1TCPSocketAction
}
