/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { V1NamespaceCondition } from './V1NamespaceCondition'

/**
 * NamespaceStatus is information about the current status of a Namespace.
 */
export interface V1NamespaceStatus {
  /**
     * Represents the latest available observations of a namespace's current state.
     */
  conditions?: Array<V1NamespaceCondition>
  /**
     * Phase is the current lifecycle phase of the namespace. More info: https://kubernetes.io/docs/tasks/administer-cluster/namespaces/
     */
  phase?: string
}
