/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { V1DaemonEndpoint } from './V1DaemonEndpoint'

/**
 * NodeDaemonEndpoints lists ports opened by daemons running on the Node.
 */
export interface V1NodeDaemonEndpoints {
  /**
     * Endpoint on which Kubelet is listening.
     */
  kubeletEndpoint?: V1DaemonEndpoint
}
