/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { V1LoadBalancerStatus } from './V1LoadBalancerStatus'
import type { V1Condition } from './v1Condition'

/**
 * ServiceStatus represents the current status of a service.
 */
export interface V1ServiceStatus {
  /**
     * Current service state
     */
  conditions?: Array<V1Condition>
  /**
     * LoadBalancer contains the current status of the load-balancer, if one is present.
     */
  loadBalancer?: V1LoadBalancerStatus
}
