/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * A topology selector requirement is a selector that matches given label. This is an alpha feature and may change in the future.
 */
export interface V1TopologySelectorLabelRequirement {
  /**
     * The label key that the selector applies to.
     */
  key: string
  /**
     * An array of string values. One value must match the label to be selected. Each entry in Values is ORed.
     */
  values: Array<string>
}
