/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { V1ConfigMapProjection } from './V1ConfigMapProjection'
import type { V1DownwardAPIProjection } from './V1DownwardAPIProjection'
import type { V1SecretProjection } from './V1SecretProjection'
import type { V1ServiceAccountTokenProjection } from './V1ServiceAccountTokenProjection'

/**
 * Projection that may be projected along with other supported volume types
 */
export interface V1VolumeProjection {
  /**
     * configMap information about the configMap data to project
     */
  configMap?: V1ConfigMapProjection
  /**
     * downwardAPI information about the downwardAPI data to project
     */
  downwardAPI?: V1DownwardAPIProjection
  /**
     * secret information about the secret data to project
     */
  secret?: V1SecretProjection
  /**
     * serviceAccountToken is information about the serviceAccountToken data to project
     */
  serviceAccountToken?: V1ServiceAccountTokenProjection
}
