export enum ResType {
  Pods = 'pods',
  Namespaces = 'namespaces',
  Deployments = 'deployments',
  Nodes = 'nodes',
  ReplicaSets = 'replicasets',
  Events = 'events',
  DaemonSets = 'daemonsets',
  StatefulSets = 'statefulsets',
  ReplicationControllers = 'replicationcontrollers',
  Jobs = 'jobs',
  CronJobs = 'cronjobs',
  ConfigMaps = 'configmaps',
  Secrets = 'secrets',
}
